using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyVideoGameList.Server.Data.Migrations
{
    /// <summary>
    /// Swaps <c>UserGameEntries</c> from a composite <c>(UserId, GameId)</c> primary key to a
    /// surrogate <c>Id</c>, keeping the old key as a unique index, and adds the wishlist axis.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>This one scaffolded correctly, unusually — check the SQL anyway if it is ever
    /// regenerated.</strong> EF has produced drop-and-recreate for this table before. The shape
    /// that must survive is: drop the constraint, add the column, add the new constraint, index.
    /// Verify with <c>dotnet ef migrations script</c> and look for <c>DROP TABLE</c>.
    /// </para>
    /// <para>
    /// Safe on a populated table: <c>GENERATED BY DEFAULT AS IDENTITY</c> rewrites the table and
    /// assigns every existing row a value, so the new primary key is unique from the first
    /// statement. A <c>defaultValue</c> on that column would break it — every row would get the
    /// same number and the primary key would fail.
    /// </para>
    /// </remarks>
    public partial class AddEntrySurrogateKeyAndWishlist : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_UserGameEntries",
                table: "UserGameEntries");

            migrationBuilder.AddColumn<int>(
                name: "Id",
                table: "UserGameEntries",
                type: "integer",
                nullable: false,
                defaultValue: 0)
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserGameEntries",
                table: "UserGameEntries",
                column: "Id");

            migrationBuilder.CreateTable(
                name: "UserWishlistItems",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "text", nullable: false),
                    GameId = table.Column<int>(type: "integer", nullable: false),
                    AddedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserWishlistItems", x => new { x.UserId, x.GameId });
                    table.ForeignKey(
                        name: "FK_UserWishlistItems_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_UserGameEntries_UserId_GameId",
                table: "UserGameEntries",
                columns: new[] { "UserId", "GameId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_UserWishlistItems_UserId_AddedAt",
                table: "UserWishlistItems",
                columns: new[] { "UserId", "AddedAt" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserWishlistItems");

            migrationBuilder.DropPrimaryKey(
                name: "PK_UserGameEntries",
                table: "UserGameEntries");

            migrationBuilder.DropIndex(
                name: "IX_UserGameEntries_UserId_GameId",
                table: "UserGameEntries");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "UserGameEntries");

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserGameEntries",
                table: "UserGameEntries",
                columns: new[] { "UserId", "GameId" });
        }
    }
}
