// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyVideoGameList.Server.Data;

#nullable disable

namespace MyVideoGameList.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421125140_AddUserGameLists")]
    partial class AddUserGameLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Japan",
                            Description = "Japanese video game developer known for challenging action RPGs.",
                            FoundedYear = 1986,
                            Name = "FromSoftware",
                            Website = "https://www.fromsoftware.jp"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Japan",
                            Description = "Nintendo's internal development division responsible for major first-party titles.",
                            FoundedYear = 2015,
                            Name = "Nintendo EPD",
                            Website = "https://www.nintendo.com"
                        },
                        new
                        {
                            Id = 3,
                            Country = "United States",
                            Description = "Sony's first-party studio and creator of the God of War series.",
                            FoundedYear = 1999,
                            Name = "Santa Monica Studio",
                            Website = "https://sms.playstation.com"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Poland",
                            Description = "Polish studio behind The Witcher series and Cyberpunk 2077.",
                            FoundedYear = 2002,
                            Name = "CD Projekt RED",
                            Website = "https://www.cdprojektred.com"
                        },
                        new
                        {
                            Id = 5,
                            Country = "United States",
                            Description = "Independent studio known for Bastion, Transistor, Pyre, and Hades.",
                            FoundedYear = 2009,
                            Name = "Supergiant Games",
                            Website = "https://www.supergiantgames.com"
                        });
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EsrbRating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MetacriticScore")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg",
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg",
                            Description = "A fantasy action RPG set in the Lands Between, co-created by Hidetaka Miyazaki and George R. R. Martin. Players explore a vast open world, battle fearsome bosses, and unravel the mystery of the shattered Elden Ring.",
                            EsrbRating = "M",
                            MetacriticScore = 96,
                            Rating = 9.5f,
                            ReleaseDate = new DateOnly(2022, 2, 25),
                            Title = "Elden Ring",
                            TrailerUrl = "https://www.youtube.com/watch?v=E3Huy2cdih0",
                            Website = "https://en.bandainamcoent.eu/elden-ring/elden-ring"
                        },
                        new
                        {
                            Id = 2,
                            BackgroundImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg",
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg",
                            Description = "An open-world action-adventure game in which Link awakens from a long slumber to defeat Calamity Ganon. Players explore the vast kingdom of Hyrule with complete freedom and unparalleled creativity.",
                            EsrbRating = "E10+",
                            MetacriticScore = 97,
                            Rating = 9.7f,
                            ReleaseDate = new DateOnly(2017, 3, 3),
                            Title = "The Legend of Zelda: Breath of the Wild",
                            TrailerUrl = "https://www.youtube.com/watch?v=zw47_q9wbBE",
                            Website = "https://www.zelda.com/breath-of-the-wild/"
                        },
                        new
                        {
                            Id = 3,
                            BackgroundImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg",
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg",
                            Description = "Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for war. Facing an imminent Ragnarök, they must decide which path to take.",
                            EsrbRating = "M",
                            MetacriticScore = 94,
                            Rating = 9.4f,
                            ReleaseDate = new DateOnly(2022, 11, 9),
                            Title = "God of War Ragnarök",
                            TrailerUrl = "https://www.youtube.com/watch?v=7XFi6Fjo4Ek",
                            Website = "https://www.playstation.com/en-us/games/god-of-war-ragnarok/"
                        },
                        new
                        {
                            Id = 4,
                            BackgroundImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg",
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg",
                            Description = "An open-world action RPG set in the megalopolis of Night City. Players take on the role of V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
                            EsrbRating = "M",
                            MetacriticScore = 86,
                            Rating = 8.5f,
                            ReleaseDate = new DateOnly(2020, 12, 10),
                            Title = "Cyberpunk 2077",
                            TrailerUrl = "https://www.youtube.com/watch?v=qIcTM8WXFjk",
                            Website = "https://www.cyberpunk.net"
                        },
                        new
                        {
                            Id = 5,
                            BackgroundImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/cc/Hades_cover_art.jpg",
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/cc/Hades_cover_art.jpg",
                            Description = "A rogue-like dungeon crawler in which the player takes on the role of Prince Zagreus, the son of Hades, attempting to escape from the Underworld. Each escape attempt features procedurally generated rooms.",
                            EsrbRating = "T",
                            MetacriticScore = 93,
                            Rating = 9.3f,
                            ReleaseDate = new DateOnly(2020, 9, 17),
                            Title = "Hades",
                            TrailerUrl = "https://www.youtube.com/watch?v=91t0ha9x0AE",
                            Website = "https://www.supergiantgames.com/games/hades/"
                        });
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.GameDeveloper", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "DeveloperId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("GameDevelopers");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            DeveloperId = 1
                        },
                        new
                        {
                            GameId = 2,
                            DeveloperId = 2
                        },
                        new
                        {
                            GameId = 3,
                            DeveloperId = 3
                        },
                        new
                        {
                            GameId = 4,
                            DeveloperId = 4
                        },
                        new
                        {
                            GameId = 5,
                            DeveloperId = 5
                        });
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 6
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 1
                        });
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.GamePlatform", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatforms");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            PlatformId = 1
                        },
                        new
                        {
                            GameId = 1,
                            PlatformId = 2
                        },
                        new
                        {
                            GameId = 1,
                            PlatformId = 3
                        },
                        new
                        {
                            GameId = 1,
                            PlatformId = 4
                        },
                        new
                        {
                            GameId = 1,
                            PlatformId = 5
                        },
                        new
                        {
                            GameId = 2,
                            PlatformId = 6
                        },
                        new
                        {
                            GameId = 3,
                            PlatformId = 2
                        },
                        new
                        {
                            GameId = 3,
                            PlatformId = 3
                        },
                        new
                        {
                            GameId = 3,
                            PlatformId = 1
                        },
                        new
                        {
                            GameId = 4,
                            PlatformId = 1
                        },
                        new
                        {
                            GameId = 4,
                            PlatformId = 2
                        },
                        new
                        {
                            GameId = 4,
                            PlatformId = 3
                        },
                        new
                        {
                            GameId = 4,
                            PlatformId = 4
                        },
                        new
                        {
                            GameId = 4,
                            PlatformId = 5
                        },
                        new
                        {
                            GameId = 5,
                            PlatformId = 1
                        },
                        new
                        {
                            GameId = 5,
                            PlatformId = 6
                        },
                        new
                        {
                            GameId = 5,
                            PlatformId = 2
                        },
                        new
                        {
                            GameId = 5,
                            PlatformId = 3
                        },
                        new
                        {
                            GameId = 5,
                            PlatformId = 4
                        },
                        new
                        {
                            GameId = 5,
                            PlatformId = 5
                        });
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.GamePublisher", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "PublisherId");

                    b.HasIndex("PublisherId");

                    b.ToTable("GamePublishers");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            PublisherId = 1
                        },
                        new
                        {
                            GameId = 2,
                            PublisherId = 2
                        },
                        new
                        {
                            GameId = 3,
                            PublisherId = 3
                        },
                        new
                        {
                            GameId = 4,
                            PublisherId = 4
                        },
                        new
                        {
                            GameId = 5,
                            PublisherId = 5
                        });
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Action game with role-playing elements",
                            Name = "Action RPG"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Combines action and adventure gameplay",
                            Name = "Action-Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Large explorable game world",
                            Name = "Open World"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Procedurally generated levels with permadeath",
                            Name = "Roguelike"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Shooter game from a first-person perspective",
                            Name = "First-Person Shooter"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Story-driven game with character progression",
                            Name = "Role-Playing Game"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Navigate platforms and obstacles",
                            Name = "Platformer"
                        });
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "PC",
                            Manufacturer = "Various",
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "PS5",
                            Manufacturer = "Sony",
                            Name = "PlayStation 5"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "PS4",
                            Manufacturer = "Sony",
                            Name = "PlayStation 4"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "XSX",
                            Manufacturer = "Microsoft",
                            Name = "Xbox Series X|S"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "XBO",
                            Manufacturer = "Microsoft",
                            Name = "Xbox One"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "NSW",
                            Manufacturer = "Nintendo",
                            Name = "Nintendo Switch"
                        });
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Japan",
                            Description = "Major Japanese publisher and co-publisher of Elden Ring.",
                            FoundedYear = 2005,
                            Name = "Bandai Namco Entertainment",
                            Website = "https://www.bandainamcoent.com"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Japan",
                            Description = "Japanese multinational video game company.",
                            FoundedYear = 1889,
                            Name = "Nintendo",
                            Website = "https://www.nintendo.com"
                        },
                        new
                        {
                            Id = 3,
                            Country = "United States",
                            Description = "Publisher of PlayStation first-party titles.",
                            FoundedYear = 1993,
                            Name = "Sony Interactive Entertainment",
                            Website = "https://www.playstation.com"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Poland",
                            Description = "Polish video game publisher and parent company of CD Projekt RED.",
                            FoundedYear = 1994,
                            Name = "CD Projekt",
                            Website = "https://www.cdprojekt.com"
                        },
                        new
                        {
                            Id = 5,
                            Country = "United States",
                            Description = "Independent studio that self-publishes its own games.",
                            FoundedYear = 2009,
                            Name = "Supergiant Games",
                            Website = "https://www.supergiantgames.com"
                        });
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.UserGameList", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "GameId");

                    b.ToTable("UserGameLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyVideoGameList.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyVideoGameList.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyVideoGameList.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyVideoGameList.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.GameDeveloper", b =>
                {
                    b.HasOne("MyVideoGameList.Server.Models.Developer", "Developer")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyVideoGameList.Server.Models.Game", "Game")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.GameGenre", b =>
                {
                    b.HasOne("MyVideoGameList.Server.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyVideoGameList.Server.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.GamePlatform", b =>
                {
                    b.HasOne("MyVideoGameList.Server.Models.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyVideoGameList.Server.Models.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.GamePublisher", b =>
                {
                    b.HasOne("MyVideoGameList.Server.Models.Game", "Game")
                        .WithMany("GamePublishers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyVideoGameList.Server.Models.Publisher", "Publisher")
                        .WithMany("GamePublishers")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.UserGameList", b =>
                {
                    b.HasOne("MyVideoGameList.Server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Developer", b =>
                {
                    b.Navigation("GameDevelopers");
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Game", b =>
                {
                    b.Navigation("GameDevelopers");

                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");

                    b.Navigation("GamePublishers");
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("MyVideoGameList.Server.Models.Publisher", b =>
                {
                    b.Navigation("GamePublishers");
                });
#pragma warning restore 612, 618
        }
    }
}
